# Create persistent volume claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: bggdb-pvc
  namespace: bggns
  labels:
    name : bggdb-pvc
spec:
  accessModes:
  - ReadWriteOnce
  #- ReadOnlyMany -> not supported by digitalocean
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage
# Create deployment with database pod
---
apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: bggdb-deploy
  namespace: bggns
  labels:
    name: bggdb-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: bggdb-po
  template: 
    metadata:
      name: bggdb-po
      namespace: bggns
      labels:
        name: bggdb-po
    spec:
      volumes:
        - name: data-vol
          persistentVolumeClaim:
             claimName: bggdb-pvc
      containers:
      - name: bggdb-db
        image: stackupiss/bgg-database:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
# Create service for DB
---
apiVersion: v1
kind: Service
metadata: 
  name: bggdb-svc
  namespace: bggns
  labels:
    name: bggdb-svc
spec:
  type: ClusterIP
  selector:
    name: bggdb-po
  ports:
    - port: 3306
      targetPort: 3306