# Create deployment with application pods
---
apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: bggapp-deploy
  namespace: bggns
  labels:
    name: bggapp-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      name: bggapp-po
  template: 
    metadata:
      name: bggapp-po
      namespace: bggns
      labels:
        name: bggapp-po
    spec:
      containers:
      - name: bggapp-po
        image: stackupiss/bgg-backend:v1
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: dbconn-cfgmap
        - secretRef:
            name: dbpwd-secret
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
# Create service for apps
---
apiVersion: v1
kind: Service
metadata: 
  name: bggapp-svc
  namespace: bggns
  labels:
    name: bggapp-svc
spec:
  type: LoadBalancer
  selector:
    name: bggapp-po
  ports:
    - port: 80
      targetPort: 3000