# Create deployment with database pods
---
apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: bggdb-deploy
  namespace: bggns
  labels:
    name: bggdb-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: bggdb-po
  template: 
    metadata:
      name: bggdb-po
      namespace: bggns
      labels:
        name: bggdb-po
    spec:
      containers:
      - name: bggdb-po
        image: stackupiss/bgg-database:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
# Create service for DB
---
apiVersion: v1
kind: Service
metadata: 
  name: bggdb-svc
  namespace: bggns
  labels:
    name: bggdb-svc
spec:
  type: ClusterIP
  selector:
    name: bggdb-po
  ports:
    - port: 3306
      targetPort: 3306