# Create namespace
---
apiVersion: v1
kind: Namespace
metadata: 
  name: bggns
  labels:
    name: bggns
# Create configmap with DB connection details
---
apiVersion: v1
kind: ConfigMap
metadata: 
  name: dbconn-cfgmap
  namespace: bggns
  labels:
    name: dbconn-cfgmap
data:
  BGG_DB_USER: root
  BGG_DB_HOST: bggdb-svc.bggns.svc.cluster.local
# Create secret with DB login
---
apiVersion: v1
kind: Secret
metadata: 
  name: dbpwd-secret
  namespace: bggns
  labels:
    name: dbpwd-secret
type: Opaque
data:
  BGG_DB_PASSWORD: Y2hhbmdlaXQ=